version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 5100:5100
    container_name: node
    # uncomment below for development 
    # with nodemon 
    volumes:
      - ./app:/usr/src/app:cached
    
  nginx:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: nginx
    ports:
      - 5001:80
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_SITE_BASEURL: '/mongo'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
volumes:
  mongodata:
