version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    container_name: node
    volumes:
      # - ./app:/usr/src/app:cached
      # comment out the shared if debugging
      # the creation of live files
      - shared:/usr/src/app/temp

  cron:
    build:
      context: .
      dockerfile: ./cron.Dockerfile
    container_name: cron
    volumes:
      - shared:/usr/src/app/temp
    env_file:
      - .env
    
  nginx:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: nginx
    ports:
      - $WEB_PORT:8081
    # volumes:
    #   - ./server/default.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGOINIT
      MONGO_INITDB_ROOT_PASSWORD: $MONGOINITPASS
    container_name: mongo
    ports:
      - $MONGO_PORT:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGOINIT}:${MONGOINITPASS}@mongo:27017/"
      ME_CONFIG_SITE_BASEURL: '/mongo'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    volumes:
      - mongodb_config:/data/configdb
    
volumes:
  mongodata:
  mongodb_config:
  shared:
