version: "3.9"
services:
  main-ftp:
    build:
      context: .
      dockerfile: .
    # image: krstphr/main_api:latest
    ports:
      - 5100:5100
    container_name: main_ftp
    # env_file:
    #   - ./app/config/.env 
    # uncomment below for development 
    # with nodemon 

    volumes:
      - ./app:/usr/src/app:cached
  redis:
    image: redis
    ports:
      - 6379:6379
      
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
